BudgetManager/BudgetManager/Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BudgetManager.Models;

namespace BudgetManager.Controllers
{
    public class OperationController : Controller
    {
        BudgetManager.Models.BM_DataBaseEntities db = new BM_DataBaseEntities();
        // GET: Operations
        public ActionResult Index()
        {
            if (Session["IdUser"] != null)
            {
                var operations = db.Operation.ToList().OrderByDescending(x=>x.Date).Take(10).ToList(); //chequear esto
                var count = db.Operation.Count();
                ViewBag.Balance = Balance();
                return View(operations);
            }
            else return RedirectToAction("Index", "Home");
        }

        public ActionResult AddOperation()
        {
            if (Session["IdUser"] != null)
            {
                ViewBag.Categories = new SelectList(db.Category, "IdCategory", "Name").OrderBy(x => x.Text);
                return View();
            }
            else return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult AddOperation(Operation operation)
        {
            _ = int.TryParse(Session["IdUser"].ToString(), out int x);
            operation.IdUser = x;
            if (ModelState.IsValid)
            {
                db.Operation.Add(operation);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(operation);
        }
        public ActionResult EditOperation(int id)
        {
            var operation = db.Operation.Find(id);
            return View(operation);
        }
        [HttpPost]
        public ActionResult EditOperation(Operation operation)
        {
            if (Session["IdUser"] != null) //el objeto no se esta pasando correctamente, solo trae Concept y Value
            {
                if (ModelState.IsValid)
                {
                    db.Entry(operation).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(operation);
            }
            else return RedirectToAction("Index", "Home");
        }
        public ActionResult DeleteOperation(int Id)
        {
            var operation = db.Operation.Find(Id);
            db.Operation.Remove(operation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private bool Validation(Operation op)
        {
            bool result = false;
            return result;
        }

        public decimal Balance()
        {
            decimal total = 0;
            foreach(Operation op in db.Operation.ToList())
            {
                if (op.Category.Type == "Income")
                    total = total + op.Value;
                else
                    total = total - op.Value;
            }
            return total;
        }
    }
}

BudgetManager/BudgetManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @if (Session["IdUser"] != null)
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Budget Manager", "Index", "Operation", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Operations", "Index", "Operation")</li>
                    </ul>
                </div>
            </div>
        </div>
    }
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom">
            <p>&copy; @DateTime.Now.Year - Budget Manager</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>